### ISSUE TITLE
Try Hack font

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/html-to-hyperscript#3]
http://sourcefoundry.org/hack/

**Comment by scabbiaza** [comment]
Added `Hack` font. I personally don't like it, but think we can keep it.
Pushed directly to the master, sorry.

**Consolas**
![consolas](https://cloud.githubusercontent.com/assets/2734464/12038078/a97aa886-ae5d-11e5-9199-d02ddbf5804b.png)

**Hack**
![hack](https://cloud.githubusercontent.com/assets/2734464/12038077/a5deb028-ae5d-11e5-83b0-99f846b7127c.png)

**Default monospace**
![monospace](https://cloud.githubusercontent.com/assets/2734464/12038074/a12bff90-ae5d-11e5-8df0-6f996b7609a3.png)

**Comment by ivan-kleshnin** [comment]
Closed by a7700b4d133b37a9ec0d563495ec7d503925ac9a
